title: Shivam Kumar
description: <a href="mailto:skumar9@nd.edu"><img src="/gmail.png" width="25" height="25"></a>  <a href="https://www.linkedin.com/in/spatnakr/"><img src="/linkedin.png" width="25" height="25"></a>  <a href="https://scholar.google.com/citations?user=cJI6e3cAAAAJ&hl=en"><img src="/google-scholar.png" width="25" height="25"></a> <a href="https://github.com/civamkr/"><img src="/github.png" width="25" height="25"></a>
theme: jekyll-theme-minimal
